[package]
name = "udcn-common"
version = "0.1.0"
edition = "2021"

license.workspace = true

[dependencies]
aya = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }

[features]
default = []
user = ["aya"]
std = []

[lib]
path = "src/lib.rs"
